name: CI/CD Pipeline for Games

on:
  push:
    branches:
      - main # Jalankan hanya saat ada perubahan di branch "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy the application to the VPS
      - name: Deploy to GCP
        run: |
          sshpass -p "${{ secrets.GCP_PASSWORD_STAGING }}" ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USER_STAGING }} << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Ini memuat nvm
            
            cd games/${{ secrets.DIRECTORY_PATH_STAGING }}
            git pull origin main

            pm2 restart ${{ secrets.DIRECTORY_PATH_STAGING }}
            pm2 save

          EOF
